config/routes.rb
Rails.application.routes.draw do

get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'
delete 'photos' => 'photos#destroy'    
get 'show' => 'photos#show'
get 'signup' => 'users#new'
    
get  '/vote' => 'photos#vote', as: :vote
resources :users, :photos, :sessions
    

  root 'pages#show', page: "home"    

end

app/models/photo.rb
class Photo < ActiveRecord::Base
    belongs_to :user

    has_many :voting_users, through: :user_votes
    has_many :user_votes

    mount_uploader :avatar, AvatarUploader

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :photos
    has_many :voted_photos, through: :user_votes
    has_many :user_votes

    has_secure_password 
    validates_confirmation_of :password
    validates_presence_of :password, on: :create

    # scope :photo_today, lambda{ where(:created_at => (Time.now.beginning_of_day..Time.now.end_of_day)) }
    # scope :photo_today, -> { where("createdAt BETWEEN ? AND ?", Time.now - (60 * 60 * 24), Time.now) }

    def uploaded_today?
        if !self.photos.empty?
           self.photos.last.created_at.to_i.between?(Time.now.to_i - (60 * 60 * 24), Time.now.to_i)
       else
        false
    end

end

end

app/models/user_vote.rb
class UserVote < ActiveRecord::Base
    belongs_to :voting_user, class_name: "User", foreign_key: :user_id
    belongs_to :voted_photo, class_name: "Photo", foreign_key: :photo_id
end


# The model with the foreign key (the id of another model) will belong to that other model

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    
    include SessionsHelper
    
    before_action :current_user
    def current_user
        if session[:user_id]
	  	        @current_user = User.find(session[:user_id])
	       end
	   end
     helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def show
        render template: "pages/#{params[:page]}"
    end
   
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :set_photo, only: [:show, :edit, :update, :destroy]
    before_action :current_user, only: :destroy
    
    def vote
        puts "VOTING WITH #{params}"
        @photo = Photo.find(params[:id])
        @photo.vote+=1
        @photo.voting_users.push current_user
        @photo.save
#        redirect_to photos_path
    end
  # GET /photos
  # GET /photos.json
  def index
    @photos =Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @user = User.find_by(params[:user_id])
    @photo = Photo.find(photo_params)
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
      @photo = Photo.new(photo_params)
      @photo.vote =0
    respond_to do |format|
      if @photo.save
          current_user.photos.push @photo
          format.html { redirect_to photos_path, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }

      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
      # @photo is pulling Photo's information 
      @photo = Photo.find(params[:id])
      # @photo_id is keeping the photos id
      @photo_id = @photo.id
      # Is destroying the photo
      @photo.destroy
      # @photo = current_user.photos.find_by(id: params[:id])
      # redirect_to root_url if @photo.nil?
      # redirect_to photos_path
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
#      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:user_id, :avatar, :body, :vote)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            log_in user

            redirect_to photos_path 
        else
            flash.now[:danger] = 'Invalid username/password combination'
            render 'new'
        end
    end

    def destroy
        log_out if logged_in?
        redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
    @user = User.all
#    #checks to see if there is a user logged in
#    current_user
end

def new
    @user = User.new
end

def show
    @user = User.find(params[:id])
end

def create
    @user = User.new(user_params)
    if @user.save
        redirect_to login_path
    else
        render 'new'
    end
end

def edit
    @user = User.find(params[:id])
end

def update
    puts "UPDATING"
    puts params
    @user = User.find(params[:id])
    redirect_to user_path @user
end

def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
end

private
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the user.
    def log_in(user)
        session[:user_id] = user.id
    end

    # gives the current logged-in user if currently loggedin
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/layouts/_nav.html.erb
 <div id="list">
        <ul>
            <% if current_user %>
            <li><%= link_to "Log out", logout_path, method: :delete, :style=>"color: white; font-family: 'Indie Flower', cursive; text-decoration: none; background: none; font-size: 4vh;"%></li>
            <% else %>
            <li><%= link_to "Log in", login_path, {style: "color: white; font-family: 'Indie Flower', cursive; text-decoration: none; background: none; font-size: 4vh; "} %></li>
            <% end %>
            
            <li><%= link_to "Explore", photos_path, {style: "color: white; font-family: 'Indie Flower', cursive; text-decoration: none; background: none; font-size: 4vh;"} %></li>   
            <% if current_user %>

            <li><%= link_to "#{current_user.username}", user_path(current_user.id), {style: "color: white; font-family: 'Indie Flower', cursive; text-decoration: none; background: none; font-size: 4vh;"} %></li>
            <%end%>
        </ul>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
      <![endif]-->
      <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
      <script src="//code.jquery.com/jquery-1.10.2.js"></script>
      <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
      <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Comfortaa:700' rel='stylesheet' type='text/css'>
  </head>


  <body>

    <%= yield %>
    <%= render 'layouts/nav'%>
</body>
</html>    

app/views/pages/home.html.erb
<div class="homeContent">

    <div id="header">
        <%= image_tag("Camera.png", :size => "150x150") %>
    </div>  
</div>

app/views/photos/_form.html.erb
<%= form_for Photo.new, :html => {:multipart => true} do |f| %>
 
  <p>
    <%= f.file_field :avatar %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/photos/destroy.js.erb
// its getting id image-#{p.id} from index.html.erb
console.log($("#image-" + "<%= @photo_id%>"));
// getting the image and fading it 3 seconds after click
$("#image-" + "<%= @photo_id%>").fadeOut(3000);

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Photos</h1>
<br>
<div class="row">
    <% @photos.each do |p| %>
    <!-- gave it a class of col-xs-6 col-md-3 with an id of "image-#{p.id}" -->
    <%= content_tag :span, class:"col-xs-6 col-md-3", id: "image-#{p.id}" do%>
    <!-- printing out picture with a max-height of 200px -->
    <%= image_tag p.avatar_url , class: "explore-image"%>
    <br />
    <!-- link that deletes the photo  -->
    <% if current_user == p.user%>
    <%= link_to "Delete",  photo_path(p.id),  method: :delete, remote: :true %>
    <%end%>
    &nbsp;&nbsp;&nbsp;
    <%= link_to "Like", vote_path(id: p.id), remote: :true %>
    <%= content_tag :h5, p.vote, id: "photo-#{p.id}" %>
    <%end%>
    <% end %>
</div>

<% if current_user %>
<% if !current_user.uploaded_today? %>
<div id="row">
    <h1>Upload Your Daily Photo</h1>
    <div class="column_s">
        <%= render 'form' %>
    </div>
</div>
<%end%>
<%end%>

app/views/photos/show.html.erb
<%= link_to 'Back', photos_path %>

<%= image_tag @photo.avatar %>

app/views/photos/vote.js.erb
//alert("HELLO")
$('#photo-<%= @photo.id%>').text("<%= @photo.vote %>");

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <!-- <div class="field">
    <%= f.label :total_likes %><br>
    <%= f.number_field :total_likes %>
  </div> -->
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<style type='text/css'>

 html { 
      background: url(/assets/signup.jpeg) no-repeat center center fixed; 
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }
    
</style>

    <div id="row">
        <h1>Sign up</h1>
        <div class="col-md-6 col-md-offset-3">
            <%= form_for(@user) do |f| %>
            <%= f.label :username %><br>
            <%= f.text_field :username %>

            <br><%= f.label :password %><br>
            <%= f.password_field :password %>

            <br><%= f.label :password_confirmation, "Confirmation" %><br>
            <%= f.password_field :password_confirmation %>
                <br><br>
            <%= f.submit "Create", class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>

app/views/users/show.html.erb
<div class="row">

  <div class="col-sm-8 col-sm-offset-2">
    <div class="white">
      <h1>Welcome
        <%= @user.username %> 
      </h1>
      
      <br/>
      <%= "Name: #{@user.name}" if @user.name %>  <br/>
      <strong>Likes:</strong>
      <%= @user.total_likes %>  <br/>
      <%= content_tag :h2, "You have uploaded #{@user.photos.count} photo(s)" %>  <br/>

      <% if !current_user.uploaded_today? %>
      <strong>Upload a photo today:</strong>
      <%= render 'photos/form'%>
      <%end%>

      <%= link_to 'Edit', edit_user_path(@user) %>
      <%= link_to 'Back to Photos', photos_path %>
    </div>
  </div>
</div>    

<div class="row">

  <div class="col-sm-8 col-sm-offset-2">
    <div class="white">

      <% current_user.photos.each do |p|%>
        <%= image_tag p.avatar_url, class: "explore-image" %>
      <%end%>

    </div>
  </div>
</div>